#!/bin/bash

# This script installs the POTSBLIZ rotary plugin

echo "Installing POTSBLIZ rotary plugin ..."

# determine script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# copy python scripts
PYTHON_DIST_DIR=/usr/local/lib/python2.7/dist-packages
mkdir -v -p $PYTHON_DIST_DIR/potsbliz/plugin/rotary
touch $PYTHON_DIST_DIR/potsbliz/plugin/__init__.py
cp $DIR/*.py $PYTHON_DIST_DIR/potsbliz/plugin/rotary

# copy startup script
cp -v $DIR/potsbliz-plugin-rotary /etc/init.d

# create and start daemon
update-rc.d potsbliz-plugin-rotary defaults
/etc/init.d/potsbliz-plugin-rotary start

echo "POTSBLIZ rotary plugin installed."
