#!/bin/bash

# This script installs the POTSBLIZ software on Raspberry PI from scratch
# Preconditions:
# up-to-date raspbian linux (via apt-get update and apt-get upgrade)
# timezone configured (via dpkg-reconfigure tzdata or raspi-config)
# locales configured (via dpkg-reconfigure locales or raspi-config , e.g. de_DE.UTF-8)

if [[ $EUID -ne 0 ]]; then
  echo "This install script requires root privileges"
  exit 1
fi

echo "Installing POTSBLIZ (Plain Old Telephone Service Beyond Local IP Stack) ..."

# change into script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CWD=$(pwd)
cd $DIR


# preconfigure packages
export MYSQL_ROOT_PASSWORD=potsbliz
echo "mysql-server-5.5 mysql-server/root_password password ${MYSQL_ROOT_PASSWORD}
mysql-server-5.5 mysql-server/root_password seen true
mysql-server-5.5 mysql-server/root_password_again password ${MYSQL_ROOT_PASSWORD}
mysql-server-5.5 mysql-server/root_password_again seen true
" | debconf-set-selections
echo 'libc6 libraries/restart-without-asking boolean true' | sudo debconf-set-selections


echo "Install required debian packages ..."
cat package-list | xargs apt-get -y install


# store version info
git describe > /etc/potsbliz.version


# set hostname (useful at least for bluetooth pairing and maybe other things)
mv /etc/hostname /etc/hostname.orig 
echo 'POTSBLIZ' > /etc/hostname


# create dbus config file
cat <<EOF > /etc/dbus-1/system.d/potsbliz.conf
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

  <!-- ../system.conf have denied everything, so we just punch some holes -->

  <policy user="root">
    <allow own="net.longexposure.potsbliz"/>
    <allow send_destination="net.longexposure.potsbliz"/>
  </policy>

  <policy user="www-data">
    <allow send_destination="net.longexposure.potsbliz"/>
  </policy>

</busconfig>
EOF


# setup apache

# setup site configuration file
cat <<EOF > /etc/apache2/sites-available/potsbliz.conf
<VirtualHost *:80>
	ServerAdmin webmaster@localhost
	DocumentRoot $DIR/apache2/www
	Alias /userpart $DIR/python/potsbliz/userpart
	AddExternalAuth pwauth /usr/sbin/pwauth
	SetExternalAuthMethod pwauth pipe
	<Directory $DIR>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride AuthConfig
		AuthName "POTSBLIZ"
		AuthType Basic
		AuthBasicProvider socache external
		AuthExternalProvideCache On
		AuthnCacheProvideFor external
		AuthExternal pwauth
		Require valid-user
		AddHandler mod_python .py
		PythonHandler mod_python.publisher
	</Directory>
	ErrorLog ${APACHE_LOG_DIR}/error.log
	LogLevel warn
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOF

# setup dbd mysql configuration file
cat <<EOF > /etc/apache2/conf-available/dbd_mysql.conf
DBDriver mysql
DBDParams "host=127.0.0.1 port=3306 user=potsbliz pass=potsbliz dbname=potsbliz"
DBDMin  2
DBDKeep 4
DBDMax  10
DBDExptime 300
EOF

# start local web server
a2dissite -q 000-default.conf
a2ensite -q potsbliz.conf
a2enmod -q dbd
a2enmod -q socache_shmcb
a2enmod -q authn_socache
a2enconf -q dbd_mysql
a2enconf -q javascript-common
service apache2 reload


# download jtable javascript library
cd /usr/share/javascript
git clone git://github.com/hikalkan/jtable.git
cd jtable
git checkout tags/v2.4.0


# create mysql database and user
echo "Creating potsbliz Mysql database ..."
echo "You will be asked for your Mysql root password ..."
mysql -u root -p$MYSQL_ROOT_PASSWORD << EOF
CREATE DATABASE IF NOT EXISTS potsbliz;
GRANT ALL ON potsbliz.* TO 'potsbliz'@'localhost' IDENTIFIED BY 'potsbliz';
FLUSH PRIVILEGES;
EOF

# init database
mysql -u potsbliz -ppotsbliz << EOF
USE potsbliz;

CREATE TABLE IF NOT EXISTS speeddial (
  id INT AUTO_INCREMENT PRIMARY KEY,
  shortcut VARCHAR(3),
  phonenumber VARCHAR(20),
  comment VARCHAR(80)
);
INSERT IGNORE INTO speeddial VALUES ('1', '21', '123456789', 'MyFirstSpeedDialNumber');
EOF

# install required python packages
pip install netifaces
pip install enum34

# make scripts executable
chmod +x $DIR/potsbliz
chmod +x $DIR/python/potsbliz/plugin/rotary/*install
chmod +x $DIR/python/potsbliz/userpart/sip/*install
chmod +x $DIR/python/potsbliz/userpart/asterisk/*install
chmod +x $DIR/python/potsbliz/userpart/bluetooth/*install

# integrate in pythonpath
ln -s $DIR/python/potsbliz /usr/local/lib/python2.7/dist-packages/potsbliz

# link console demo program into PATH
ln -s $DIR/python/potsbliz/plugin/console/__main__.py /usr/local/sbin/potsbliz

# create and start daemon
cp -v $DIR/potsbliz /etc/init.d
update-rc.d potsbliz defaults
/etc/init.d/potsbliz start

# install plugins
$DIR/python/potsbliz/plugin/rotary/install

# install userparts
$DIR/python/potsbliz/userpart/sip/install
$DIR/python/potsbliz/userpart/asterisk/install
$DIR/python/potsbliz/userpart/bluetooth/install

# restore working directory 
cd $CWD

read -p "POTSBLIZ installed. Reboot required. Reboot now (y/n)? " choice
case "$choice" in 
  y|Y ) reboot;;
  * ) echo "Remember to reboot before using POTSBLIZ!";;
esac
