#!/bin/bash

# This script installs the POTSBLIZ software on Raspberry PI from scratch
# Preconditions:
# up-to-date raspbian linux (via apt-get update and apt-get upgrade)
# timezone configured (via dpkg-reconfigure tzdata or raspi-config)
# locales configured (via dpkg-reconfigure locales or raspi-config , e.g. de_DE.UTF-8)

if [[ $EUID -ne 0 ]]; then
  echo "This install script requires root privileges"
  exit 1
fi

echo "Installing POTSBLIZ (Plain Old Telephone Service Beyond Local IP Stack) ..."

# change into script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CWD=$(pwd)
cd $DIR

# preconfigure packages
export MYSQL_ROOT_PASSWORD=potsbliz
echo "mysql-server-5.5 mysql-server/root_password password ${MYSQL_ROOT_PASSWORD}
mysql-server-5.5 mysql-server/root_password seen true
mysql-server-5.5 mysql-server/root_password_again password ${MYSQL_ROOT_PASSWORD}
mysql-server-5.5 mysql-server/root_password_again seen true
" | debconf-set-selections
echo 'libc6 libraries/restart-without-asking boolean true' | sudo debconf-set-selections

echo "Install required debian packages ..."
cat package-list | xargs apt-get -y install

# install potsbliz
PYTHON_DIST_DIR=/usr/local/lib/python2.7/dist-packages
cd $DIR
mkdir -v -p $PYTHON_DIST_DIR/potsbliz
mkdir -v -p /var/www
cp -r core/potsbliz $PYTHON_DIST_DIR
git describe > $PYTHON_DIST_DIR/potsbliz/potsbliz.version
cp -v potsbliz /etc/init.d
cp -v core/apache2/potsbliz.conf /etc/apache2/sites-available
cp -v core/apache2/dbd_mysql.conf /etc/apache2/conf-available
cp -v -r core/apache2/www /var/www/potsbliz
cp -v core/dbus-1/potsbliz.conf /etc/dbus-1/system.d

# enable local web server
a2dissite 000-default.conf
a2ensite potsbliz.conf
a2enmod dbd
a2enmod authn_dbd
a2enconf dbd_mysql
service apache2 reload

# create javascript links
ln -s /usr/share/javascript/jquery /var/www/potsbliz/jquery
ln -s /usr/share/javascript/jquery-ui /var/www/potsbliz/jquery-ui
ln -s /usr/share/javascript/jquery-ui-themes /var/www/potsbliz/jquery-ui-themes

# download jtable javascript library
cd /usr/share/javascript
git clone git://github.com/hikalkan/jtable.git
cd jtable
git checkout tags/v2.4.0
ln -s /usr/share/javascript/jtable/lib /var/www/potsbliz/jtable

# create mysql database and user
echo "Creating potsbliz Mysql database ..."
echo "You will be asked for your Mysql root password ..."
mysql -u root -p$MYSQL_ROOT_PASSWORD << EOF
CREATE DATABASE IF NOT EXISTS potsbliz;
GRANT ALL ON potsbliz.* TO 'potsbliz'@'localhost' IDENTIFIED BY 'potsbliz';
FLUSH PRIVILEGES;
EOF

# init database
mysql -u potsbliz -ppotsbliz << EOF
USE potsbliz;

CREATE TABLE IF NOT EXISTS speeddial (
  id INT AUTO_INCREMENT PRIMARY KEY,
  shortcut VARCHAR(3),
  phonenumber VARCHAR(20),
  comment VARCHAR(80)
);
INSERT IGNORE INTO speeddial VALUES ('1', '21', '123456789', 'MyFirstSpeedDialNumber');

CREATE TABLE IF NOT EXISTS mysql_auth (
  username CHAR(25) NOT NULL,
  passwd CHAR(32),
  PRIMARY KEY (username)
);
INSERT IGNORE INTO mysql_auth (username, passwd) VALUES ('admin', ENCRYPT('admin'));
EOF

# install required python packages
pip install netifaces
pip install enum34

# make scripts executable
chmod +x /etc/init.d/potsbliz
chmod +x $DIR/plugin/rotary/*install
chmod +x $DIR/userpart/sip/*install
chmod +x $DIR/userpart/asterisk/*install
chmod +x $DIR/userpart/bluetooth/*install

# create and start daemon
update-rc.d potsbliz defaults
/etc/init.d/potsbliz start

# install plugins
$DIR/plugin/rotary/install

# install userparts
$DIR/userpart/sip/install
$DIR/userpart/asterisk/install
$DIR/userpart/bluetooth/install

# restore working directory 
cd $CWD

read -p "Reboot required. Reboot now (y/n)? " choice
case "$choice" in 
  y|Y ) reboot;;
  * ) echo "Remember to reboot before using POTSBLIZ!";;
esac
