#!/bin/bash

# This script removes the POTSBLIZ software from Raspberry PI

if [[ $EUID -ne 0 ]]; then
  echo "This uninstall script requires root privileges"
  exit 1
fi


# determine script directory 
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# uninstall userparts
$DIR/userpart/bluetooth/uninstall
$DIR/userpart/asterisk/uninstall
$DIR/userpart/sip/uninstall


# uninstall plugins
$DIR/plugin/rotary/uninstall


# stop and remove daemon
/etc/init.d/potsbliz stop
update-rc.d potsbliz remove


# drop potsbliz database
mysql -u root -ppotsbliz << EOF
DROP DATABASE IF EXISTS potsbliz;
EOF


# remove potsbliz web folder
rm -R /var/www/potsbliz


# remove jtable javascript library
rm -R /usr/share/javascript/jtable


# restore original apache setup
a2dissite potsbliz.conf
a2ensite 000-default.conf
a2dismod dbd
a2dismod authn_dbd
a2disconf dbd_mysql
service apache2 reload

# restore original asterisk config
mv /etc/asterisk/sip.conf /etc/asterisk/sip_potsbliz.conf
mv /etc/asterisk/extensions.conf /etc/asterisk/extensions_potsbliz.conf
mv /etc/asterisk/sip.conf.orig /etc/asterisk/sip.conf
mv /etc/asterisk/extensions.conf.orig /etc/asterisk/extensions.conf

# remove dbus config
rm /etc/dbus-1/system.d/potsbliz*

# remove potsbliz python scripts
rm -R /usr/local/lib/python2.7/dist-packages/potsbliz


# remove installed wheezy packages
cat $DIR/package-list | xargs apt-get -y remove
apt-get -y autoremove
