#!/bin/bash

# This script removes the POTSBLIZ software from Raspberry PI

if [[ $EUID -ne 0 ]]; then
  echo "This uninstall script requires root privileges"
  exit 1
fi


# determine script directory 
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# uninstall userparts
$DIR/python/potsbliz/userpart/bluetooth/uninstall
$DIR/python/potsbliz/userpart/asterisk/uninstall
$DIR/python/potsbliz/userpart/sip/uninstall


# uninstall plugins
$DIR/python/potsbliz/plugin/rotary/uninstall


# stop and remove daemon
/etc/init.d/potsbliz stop
update-rc.d potsbliz remove
rm -v /etc/init.d/potsbliz


# cleanup PYTHONPATH
rm -v /usr/local/lib/python2.7/dist-packages/potsbliz


# drop potsbliz database
mysql -u root -ppotsbliz << EOF
DROP DATABASE IF EXISTS potsbliz;
EOF


# remove jtable javascript library
rm -R /usr/share/javascript/jtable


# restore original apache setup
a2dissite -q potsbliz.conf
a2ensite -q 000-default.conf
a2dismod -q authn_dbd
a2dismod -q dbd
a2disconf -q dbd_mysql
service apache2 reload

# remove config files
rm -v /etc/apache2/conf-available/dbd_mysql.conf
rm -v /etc/apache2/sites-available/potsbliz.conf


# remove dbus config
rm -v /etc/dbus-1/system.d/potsbliz.conf


# remove version info
rm -v /etc/potsbliz.version


# remove installed packages
cat $DIR/package-list | xargs apt-get -y remove
apt-get -y autoremove
