#!/bin/sh

# ### BEGIN INIT INFO
# Provides: potsbliz-plugin-rotary
# Required-Start: $remote_fs $syslog potsbliz
# Required-Stop: $remote_fs $syslog potsbliz
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: POTSBLIZ ROTATY - Rotary Dial Phone Plugin for POTSBLIZ
# Description:       Supports old rotary dial phones in an IP environment
### END INIT INFO

DAEMON=/usr/bin/python
ARGS="-m potsbliz.plugin.rotary"
PIDFILE=/var/run/potsbliz-plugin-rotary.pid

test -x $DAEMON || exit 0

case "$1" in

    start)
    
    echo "Starting potsbliz-plugin-rotary"
    start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- $ARGS
    ;;

    stop)
    echo "Shutting down potsbliz-plugin-rotary"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    rm $PIDFILE
    ;;

    restart)
    echo "Restarting potsbliz-plugin-rotary"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    rm $PIDFILE
    start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- $ARGS
    ;;

    status)
    if [ -f $PIDFILE ]; then
		echo '*************************************'
		echo '* POTSBLIZ-PLUGIN-ROTARY is running *'
		echo '*************************************'
	else
		echo '*****************************************'
		echo '* POTSBLIZ-PLUGIN-ROTARY is NOT running *'
		echo '*****************************************'
	fi
    ;;

    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac
exit 0
