#!/bin/bash

# This script installs the POTSBLIZ SIP userpart

echo "Installing POTSBLIZ SIP userpart ..."

# determine script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# install required packages
apt-get -y install linphone

# copy python scripts
PYTHON_DIST_DIR=/usr/local/lib/python2.7/dist-packages
mkdir -v -p $PYTHON_DIST_DIR/potsbliz/userpart/sip
cp $DIR/*.py $PYTHON_DIST_DIR/potsbliz/userpart/sip

# copy dbus config
cp -v $DIR/dbus-1/potsbliz-userpart-sip.conf /etc/dbus-1/system.d

# copy web interface
mkdir -v -p /var/www/potsbliz/plugin/sip
cp $DIR/www/* /var/www/potsbliz/plugin/sip

# copy startup script
cp -v $DIR/potsbliz-userpart-sip /etc/init.d

# enhance database
mysql -u potsbliz -ppotsbliz << EOF
USE potsbliz;
CREATE TABLE IF NOT EXISTS sip (
  id INT AUTO_INCREMENT PRIMARY KEY,
  identity VARCHAR(80),
  proxy VARCHAR(80),
  password VARCHAR(80)
);
INSERT IGNORE INTO sip VALUES ('1', 'sip:mySipId@mySipProvider.com', 'sip:mySipProxyProvider.com', 'mySecretPassword');
EOF

# make script executable
chmod +x /etc/init.d/potsbliz-userpart-sip

# create and start daemon
update-rc.d potsbliz-userpart-sip defaults
/etc/init.d/potsbliz-userpart-sip start

echo "POTSBLIZ SIP userpart installed."
