#!/bin/bash

# This script installs the POTSBLIZ bluetooth userpart

echo "Installing POTSBLIZ bluetooth userpart ..."

# change into script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CWD=$(pwd)
cd $DIR

echo "Install required debian packages ..."
cat package-list | xargs apt-get -y install

# create dbus config
cat <<EOF > /etc/dbus-1/system.d/potsbliz-userpart-bluetooth.conf
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

  <!-- ../system.conf have denied everything, so we just punch some holes -->

  <policy user="root">
    <allow own="net.longexposure.potsbliz.btup"/>
    <allow send_destination="net.longexposure.potsbliz.btup"/>
  </policy>

  <policy user="www-data">
    <allow send_destination="org.ofono"/>
    <allow send_destination="org.bluez"/>
  </policy>

</busconfig>
EOF

# set bluetooth adapter name
sudo sed -i '/#Name/a Name = Potsbliz' /etc/bluetooth/main.conf

# build and install pulseaudio
if [ ! -e /usr/local/bin/pulseaudio ]
then
    echo "Download, build and install pulseaudio (this can take hours) ..."
    cd $HOME
	git clone git://anongit.freedesktop.org/pulseaudio/pulseaudio
	cd pulseaudio
	git checkout tags/v7.0
	./autogen.sh
	make
	make install
	ldconfig
	sed -i 's/module-bluetooth-discover$/module-bluetooth-discover headset=ofono/' /usr/local/etc/pulse/default.pa
	cd ..
fi

# copy startup script
cp -v $DIR/potsbliz-userpart-bluetooth /etc/init.d

# make script executable
chmod +x /etc/init.d/potsbliz-userpart-bluetooth

# create and start daemon
update-rc.d potsbliz-userpart-bluetooth defaults
/etc/init.d/potsbliz-userpart-bluetooth start

# restore working directory 
cd $CWD

echo "POTSBLIZ bluetooth userpart installed."
