#!/bin/sh

# ### BEGIN INIT INFO
# Provides: potsbliz-userpart-bluetooth
# Required-Start: $remote_fs $syslog potsbliz
# Required-Stop: $remote_fs $syslog potsbliz
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: POTSBLIZ BLUETOOTH - Bluetooth userpart for POTSBLIZ
# Description:       Supports connection establishment via bluetooth
### END INIT INFO

DAEMON=/usr/bin/python
ARGS="-m potsbliz.userpart.bluetooth"
PIDFILE=/var/run/potsbliz-userpart-bluetooth.pid

test -x $DAEMON || exit 0

# set environment variables
[ -f /etc/default/potsbliz ] && . /etc/default/potsbliz

case "$1" in

    start)
    
    echo "Starting potsbliz-userpart-bluetooth"
    start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- $ARGS
    ;;

    stop)
    echo "Shutting down potsbliz-userpart-bluetooth"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    rm $PIDFILE
    ;;

    restart)
    echo "Restarting potsbliz-userpart-bluetooth"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    rm $PIDFILE
    start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- $ARGS
    ;;

    status)
    if [ -f $PIDFILE ]; then
		echo '******************************************'
		echo '* POTSBLIZ-USERPART-BLUETOOTH is running *'
		echo '******************************************'
	else
		echo '**********************************************'
		echo '* POTSBLIZ-USERPART-BLUETOOTH is NOT running *'
		echo '**********************************************'
	fi
    ;;

    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac
exit 0
