#!/bin/bash

# This script removes the POTSBLIZ bluetooth userpart

# stop and remove daemon
/etc/init.d/potsbliz-userpart-bluetooth stop
update-rc.d potsbliz-userpart-bluetooth remove

# this script does NOT remove the self-compiled pulseaudio software

# remove python scripts
rm -R /usr/local/lib/python2.7/dist-packages/potsbliz/userpart/bluetooth

#remove web interface
rm -R /var/www/potsbliz/plugin/bluetooth

# remove installed wheezy packages
cat $DIR/package-list | xargs apt-get -y remove
