#!/bin/bash

# This script removes the POTSBLIZ bluetooth userpart

# stop and remove daemon
/etc/init.d/potsbliz-userpart-bluetooth stop
update-rc.d potsbliz-userpart-bluetooth remove

# this script does NOT remove the self-compiled pulseaudio software

# remove dbus config
rm -v /etc/dbus-1/system.d/potsbliz-userpart-bluetooth.conf

# remove installed wheezy packages
cat $DIR/package-list | xargs apt-get -y remove
