#!/bin/bash

# This script installs the POTSBLIZ SIP userpart

echo "Installing POTSBLIZ SIP userpart ..."

# determine script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

apt-get -y install linphone

# copy startup script
cp -v $DIR/potsbliz-userpart-sip /etc/init.d

# create and start daemon
update-rc.d potsbliz-userpart-sip defaults
/etc/init.d/potsbliz-userpart-sip start

echo "POTSBLIZ SIP userpart installed."
