#!/bin/sh

# ### BEGIN INIT INFO
# Provides: potsbliz-userpart-sip
# Required-Start: $remote_fs $syslog potsbliz
# Required-Stop: $remote_fs $syslog potsbliz
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: POTSBLIZ SIP - SIP userpart for POTSBLIZ
# Description:       Supports connection establishment via the Session Initiation Protocol
### END INIT INFO

DAEMON=/usr/bin/python
ARGS="-m potsbliz.up.sip"
PIDFILE=/var/run/potsbliz-userpart-sip.pid

test -x $DAEMON || exit 0

case "$1" in

    start)
    
    echo "Starting potsbliz-userpart-sip"
    start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- $ARGS
    ;;

    stop)
    echo "Shutting down potsbliz-userpart-sip"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    rm $PIDFILE
    ;;

    restart)
    echo "Restarting potsbliz-userpart-sip"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    rm $PIDFILE
    start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- $ARGS
    ;;

    status)
    if [ -f $PIDFILE ]; then
		echo '************************************'
		echo '* POTSBLIZ-USERPART-SIP is running *'
		echo '************************************'
	else
		echo '****************************************'
		echo '* POTSBLIZ-USERPART-SIP is NOT running *'
		echo '****************************************'
	fi
    ;;

    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac
exit 0
