#!/bin/bash

# This script installs the POTSBLIZ Asterisk userpart

echo "Installing POTSBLIZ Asterisk userpart ..."

# determine script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# preconfigure packages
echo "libvpb0 libvpb0/countrycode string 49" | debconf-set-selections

# install asterisk
apt-get -y install asterisk asterisk-prompt-de asterisk-prompt-fr-armelle

# copy python scripts
PYTHON_DIST_DIR=/usr/local/lib/python2.7/dist-packages
mkdir -v -p $PYTHON_DIST_DIR/potsbliz/userpart/asterisk
cp $DIR/*.py $PYTHON_DIST_DIR/potsbliz/userpart/asterisk

# copy dbus config
cp -v $DIR/dbus-1/potsbliz-userpart-asterisk.conf /etc/dbus-1/system.d

# copy config files and agi scripts
cp -v $DIR/config/sip.conf /etc/asterisk/sip_potsbliz.conf
cp -v $DIR/config/extensions.conf /etc/asterisk/extensions_potsbliz.conf
cp -v $DIR/agi/*.agi /usr/share/asterisk/agi-bin

# patch installed asterisk PBX
mv /etc/asterisk/sip.conf /etc/asterisk/sip.conf.orig
mv /etc/asterisk/extensions.conf /etc/asterisk/extensions.conf.orig
mv /etc/asterisk/sip_potsbliz.conf /etc/asterisk/sip.conf
mv /etc/asterisk/extensions_potsbliz.conf /etc/asterisk/extensions.conf
/etc/init.d/asterisk restart

# copy startup script
cp -v $DIR/potsbliz-userpart-asterisk /etc/init.d

# make script executable
chmod +x /etc/init.d/potsbliz-userpart-asterisk

# create and start daemon
update-rc.d potsbliz-userpart-asterisk defaults
/etc/init.d/potsbliz-userpart-asterisk start

echo "POTSBLIZ Asterisk userpart installed."
