#!/bin/bash

# This script installs the POTSBLIZ SIP userpart

echo "Installing POTSBLIZ SIP userpart ..."

# determine script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# install required packages
apt-get -y install linphone

# create dbus config
cat <<EOF > /etc/dbus-1/system.d/potsbliz-userpart-sip.conf
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

  <!-- ../system.conf have denied everything, so we just punch some holes -->

  <policy user="root">
    <allow own="net.longexposure.potsbliz.ipup.port5060"/>
    <allow send_destination="net.longexposure.potsbliz.ipup.port5060"/>
  </policy>

</busconfig>
EOF

# copy startup script
cp -v $DIR/potsbliz-userpart-sip /etc/init.d

# enhance database
mysql -u potsbliz -ppotsbliz << EOF
USE potsbliz;
CREATE TABLE IF NOT EXISTS sip (
  id INT AUTO_INCREMENT PRIMARY KEY,
  identity VARCHAR(80),
  proxy VARCHAR(80),
  password VARCHAR(80)
);
INSERT IGNORE INTO sip VALUES ('1', 'sip:mySipId@mySipProvider.com', 'sip:mySipProxyProvider.com', 'mySecretPassword');
EOF

# make script executable
chmod +x /etc/init.d/potsbliz-userpart-sip

# create and start daemon
update-rc.d potsbliz-userpart-sip defaults
/etc/init.d/potsbliz-userpart-sip start

echo "POTSBLIZ SIP userpart installed."
