#!/bin/bash

# This script removes the POTSBLIZ SIP userpart

# stop and remove daemon
/etc/init.d/potsbliz-userpart-sip stop
update-rc.d potsbliz-userpart-sip remove

# remove dbus config
rm -v /etc/dbus-1/system.d/potsbliz-userpart-sip.conf

apt-get -y remove linphone
