#!/bin/bash

# This script removes the POTSBLIZ bluetooth userpart

# stop and remove daemon
/etc/init.d/potsbliz-userpart-bluetooth stop
update-rc.d potsbliz-userpart-bluetooth remove

# this script does NOT remove the self-compiled pulseaudio software

# remove bluetooth software
apt-get -y remove bluez bluez-utils libasound2-dev ofono libjson-c-dev

# remove apt pinning
rm /etc/apt/preferences

# restore apt source list
sed -i '/jessie/Id' /etc/apt/sources.list

# update package lists
apt-get update

# remove installed wheezy packages
cat $DIR/package-list | xargs apt-get -y remove
