#!/bin/bash

# This script installs the POTSBLIZ Asterisk userpart

echo "Installing POTSBLIZ Asterisk userpart ..."

# determine script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# preconfigure packages
echo "libvpb0 libvpb0/countrycode string 49" | debconf-set-selections

# install asterisk
apt-get -y install asterisk asterisk-prompt-de asterisk-prompt-fr-armelle

# create dbus config
cat <<EOF > /etc/dbus-1/system.d/potsbliz-userpart-asterisk.conf
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

  <!-- ../system.conf have denied everything, so we just punch some holes -->

  <policy user="root">
    <allow own="net.longexposure.potsbliz.ipup.port5061"/>
    <allow send_destination="net.longexposure.potsbliz.ipup.port5061"/>
  </policy>

</busconfig>
EOF

# copy config files and agi scripts
cp -v $DIR/config/sip.conf /etc/asterisk/sip_potsbliz.conf
cp -v $DIR/config/extensions.conf /etc/asterisk/extensions_potsbliz.conf
cp -v $DIR/agi/*.agi /usr/share/asterisk/agi-bin

# patch installed asterisk PBX
mv /etc/asterisk/sip.conf /etc/asterisk/sip.conf.orig
mv /etc/asterisk/extensions.conf /etc/asterisk/extensions.conf.orig
mv /etc/asterisk/sip_potsbliz.conf /etc/asterisk/sip.conf
mv /etc/asterisk/extensions_potsbliz.conf /etc/asterisk/extensions.conf
/etc/init.d/asterisk restart

# copy startup script
cp -v $DIR/potsbliz-userpart-asterisk /etc/init.d

# make scripts executable
chmod +x /etc/init.d/potsbliz-userpart-asterisk
chmod +x /usr/share/asterisk/agi-bin/*

# create and start daemon
update-rc.d potsbliz-userpart-asterisk defaults
/etc/init.d/potsbliz-userpart-asterisk start

echo "POTSBLIZ Asterisk userpart installed."
